### PR TITLE
Updated logger initialisation

### PR DESCRIPTION
**Pull request by Hugovdberg**
See #150:

* timing of the logger initialisation is changed;
* `log4r` package is attached in the global environment to provide quick access to logging functions (reverts 176b7fddefc54ffb2bbc8e29fdb9bcb1ada7ea79)
* added `logging_level` to global configuration to set the default loglevel

### CODE REVIEW

**Comment by KentonWhite** [comment]
Changes looks good. Thanks!  Couple of housekeeping requests to keep the documentation current:

- Add a short description of the new functionality to inst/defaults/full/logs/README.md

- Add a similar description to the website markdown files (search for logging to find the occurrences)

- Squash into a single commit (makes it easier to ensure the your changes are included in the news section when updating CRAN)

Thanks again for your work on ProjectTemplate!

**Comment by Hugovdberg** [comment]
How were the screenshots of the features created? Specifically `website/logging.png`, `website/_imgsrc/logging.xcf`, and `website/_imgsrc/logging.jpg` portray the old order of operations. It is maybe just a minor detail, but the whole point of the project is to strive for reproducibility, isn't it?
I can of course make a screenshot of my own setup and trim it, but maybe there's a nice trick I don't know of as of yet.

**Comment by KentonWhite** [comment]
Great catch on the screenshots. That's going the extra mile :)

There is no trick for screenshots, I just take a screen shot of my own setup and trim it.

**Comment by Hugovdberg** [comment]
I updated the screenshot, however I'm not able to reproduce the bold font nor the exact font size, would it be possible that you create a screenshot of the new setup with the same layout as the other screenshots? Or am I too much of a perfectionist now?
Are there any other changes necessary, apart from squashing the commits, to finish this pull request? Can the version number stay the same with the updated configuration? There is no backward incompatibility as far as I can see, but perhaps a minor version increase is justified?

**Comment by KentonWhite** [comment]
Perfectionism isn't a bad quality :). I would offer to make the screenshots myself if I thought they would be any better. Alas, the screenshots where made by the original creator on his machine and there is no guarantee that my machine will reproduce them exactly.

I usually wait until we need to push a new version to CRAN or there are major changes before bumping the version number. When I do that I go through the commit history and update the news file, giving everyone credit for the contributions. 

Once you have squashed the commits I'll merge the PR!

**Comment by Hugovdberg** [comment]
Ok I squashed the commits, I don't know if you got the message from my new commit only. 
Regarding the screenshots, perhaps we could include them as text instead of images. I'll see if I can set something up to replace all screenshots with a uniform layout (or better, update them all automatically). That's for another issue/PR, however.

**Comment by KentonWhite** [comment]
Thanks!

**Comment by Hugovdberg** [comment]
I just noticed you closed the PR but shouldn't it be merged first? or will you do so at a later moment?

**Comment by KentonWhite** [comment]
I thought I had merged it but guess it didn't take. Will try again...

**Pull request merged**
